name = "otto-website"
account_id = "3910072adb29ec7ee1bdcc37d532765d"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/server-entry.ts"

routes = [
  { pattern = "otto-code.me", custom_domain = true },
  { pattern = "www.otto-code.me", custom_domain = true },
]

[observability]
enabled = true

[[kv_namespaces]]
binding = "WEBSITE_CACHE"
id = "493815c47d094194b0cdb2f600457788"
