import { existsSync } from "node:fs";
import path from "node:path";
import { app } from "electron";

// Dev builds wear a navy tile (blue-900) where the release build wears black, so
// that running the installed Otto and a dev Otto side by side - the expected
// setup, see docs/development.md → "Lanes" - leaves two visually distinct
// taskbar buttons, dock tiles and tray entries instead of two identical ones.
//
// The navy art lives in packages/desktop/assets/dev/ and is generated by
// scripts/generate-brand-assets.mjs. It cannot reach a release build: nothing in
// electron-builder.yml copies that folder (`files:` ships only dist/**, and
// `extraResources:` names individual asset files), and every lookup here is
// gated on !app.isPackaged anyway. Missing dev art simply falls back to the
// normal icon, so a checkout that has not run the generator still launches.
export function resolveBrandedAssetPath(assetsDir: string, fileName: string): string {
  const releasePath = path.join(assetsDir, fileName);
  if (app.isPackaged) {
    return releasePath;
  }

  const devPath = path.join(assetsDir, "dev", fileName);
  return existsSync(devPath) ? devPath : releasePath;
}
