export const REPO_ROOT: string;
export const PROBE_ENTRY_FILE: string;
export const PROBE_PACKAGE_DIR: string;
export const PROBE_PROJECT_PATH: string;
export const PROBE_FIXTURES_DIR: string;
export const PROBE_BUILD_DIR: string;
export const SERVER_PACKAGE_ROOT: string;
export const SERVER_DIST_DIR: string;
export const SERVER_PAYLOAD_DIR: string;
